env:
  browser: true
  es6: false
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  prefer-arrow-callback: off
  import/no-dynamic-require: warn
  global-require: warn
