language: node_js

dist: xenial

node_js:
  - "13"

services:
  - postgresql
  - mysql
  - redis-server

sudo: true

before_install:
  - mysql -u root < test/setup.sql

notifications:
  email:
    on_success: never
    on_failure: always
