language: node_js

dist: xenial

node_js:
  - "13"

services:
  - postgresql
  - mysql
  - redis-server

sudo: true

before_script:
  - mysql --version
  - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - sudo systemctl restart mysql
  - sudo mysql_upgrade
  - mysql --version

before_install:
  - mysql -u root < test/setup.sql

notifications:
  email:
    on_success: never
    on_failure: always
