language: node_js

dist: xenial

node_js:
  - "13"
  - "12"
  - "10"

services:
  - postgresql
  - mysql
  - redis

sudo: true

before_install:
  - psql -d postgres -c 'CREATE TABLE users(id serial PRIMARY KEY, username VARCHAR (50) NOT NULL);' -U postgres
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      if [[ $(node -v) =~ v[1-9][0-9] ]]; then
        source ./ci_scripts/build.sh;
      fi
    fi

notifications:
  email:
    on_success: never
    on_failure: always
